#ifndef __ALGOSYSTEM_CONSTANTS_MQH__
#define __ALGOSYSTEM_CONSTANTS_MQH__

#define ALGO_SYSTEM_VERSION "1.002"

enum ENUM_ASSET_ROLE
  {
   ASSET_ROLE_UNKNOWN = 0,
   ASSET_ROLE_GOLD,
   ASSET_ROLE_SILVER,
   ASSET_ROLE_BITCOIN
  };

enum ENUM_TRADING_PROFILE
  {
   PROFILE_SCALP = 0,
   PROFILE_DAY,
   PROFILE_SWING
  };

enum ENUM_TRADING_MODE
  {
   MODE_SIGNAL_ONLY = 0,
   MODE_AUTO,
   MODE_DEBUG,
   MODE_BACKTEST
  };

enum ENUM_REGIME_TYPE
  {
   REGIME_UNKNOWN = 0,
   REGIME_TREND_UP,
   REGIME_TREND_DOWN,
   REGIME_RANGE,
   REGIME_BREAKOUT,
   REGIME_HIGH_VOLATILITY,
   REGIME_LOW_VOLATILITY,
   REGIME_UNCERTAIN
  };

enum ENUM_SIGNAL_DIRECTION
  {
   SIGNAL_NONE = 0,
   SIGNAL_LONG,
   SIGNAL_SHORT
  };

enum ENUM_STRATEGY_ID
  {
   STRATEGY_NONE = 0,
   STRATEGY_TREND_PULLBACK,
   STRATEGY_BREAKOUT,
   STRATEGY_MOMENTUM,
   STRATEGY_MEAN_REVERSION,
   STRATEGY_RELATIVE_VALUE
  };

enum ENUM_ORDER_INTENT
  {
   ORDER_INTENT_NONE = 0,
   ORDER_INTENT_OPEN_LONG,
   ORDER_INTENT_OPEN_SHORT,
   ORDER_INTENT_CLOSE,
   ORDER_INTENT_MODIFY_SL,
   ORDER_INTENT_MODIFY_TP
  };

enum ENUM_RISK_DECISION_TYPE
  {
   RISK_UNDEFINED = 0,
   RISK_APPROVED,
   RISK_REJECTED
  };

enum ENUM_LOG_LEVEL
  {
   LOG_ERROR = 0,
   LOG_WARNING,
   LOG_INFO,
   LOG_SIGNAL,
   LOG_TRADE,
   LOG_RISK,
   LOG_DEBUG,
   LOG_OPTIMIZATION
  };

enum ENUM_REJECTION_REASON
  {
   REJECT_NONE = 0,
   REJECT_INVALID_SIGNAL,
   REJECT_UNCERTAIN_REGIME,
   REJECT_SESSION,
   REJECT_SPREAD,
   REJECT_DAILY_LOSS,
   REJECT_MONTHLY_LOSS,
   REJECT_CONSECUTIVE_LOSSES,
   REJECT_POSITION_LIMIT,
   REJECT_PORTFOLIO_RISK,
   REJECT_CORRELATION,
   REJECT_INVALID_STOP,
   REJECT_INVALID_TARGET,
   REJECT_LOW_RR,
   REJECT_INVALID_VOLUME,
   REJECT_MARGIN,
   REJECT_EXECUTION,
   REJECT_DUPLICATE_SIGNAL,
   REJECT_TRADE_MODE,
   REJECT_TICK_SIZE,
   REJECT_STOPS_LEVEL,
   REJECT_FREEZE_LEVEL,
   REJECT_VOLUME_LIMIT,
   REJECT_NO_DATA,
   REJECT_INVALID_CONFIG
  };

#define MAGIC_BASE 26000000
#define MAGIC_TREND 26100000
#define MAGIC_BREAKOUT 26200000
#define MAGIC_MOMENTUM 26300000
#define MAGIC_MEAN_REVERSION 26400000
#define MAGIC_RELATIVE_VALUE 26500000

#define DEFAULT_SIGNAL_SCORE_THRESHOLD 70.0
#define DEFAULT_MIN_RR 1.50
#define DEFAULT_RISK_PERCENT 1.00
#define DEFAULT_DAILY_LOSS_LIMIT 3.00
#define DEFAULT_MONTHLY_LOSS_LIMIT 10.00

#define INVALID_DOUBLE_VALUE -DBL_MAX

#endif